# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: GithubRelease@11
  inputs:
    githubConnection: 'github akbarmdmd'
    repositoryName: akbarmdmd/vue
    assets: $(build.artifactstagingdirectory)/*.zip
    action: 'create'
    target: '$(build.sourceVersion)'
    tagSource: 'auto'
    #tag: # Required when action == edit || action == discard || tagSource == manual
    title: 'Tag Title'
    assetUploadMode: 'delete'
    isDraft: true
